### PR TITLE
Compute new items based on number of items on the screen fix #31

### LINKED ISSUE #31: First "page" not quite right
First off, excellent work on this much needed utility. 

I am experiencing a strange issue where the first set of data has very odd behavior. In my particular case, if I scroll the data stops displaying at row 57. However, as I keep scrolling, once row 57 reaches the top of the grid, suddenly rows 58-xx become visible as expected. All scrolling works perfectly after this first "page" of data. 

This is also true in reverse. If I scroll backwards everything works perfectly until I hit row 57 (now at the top of the grid). Once I hit that row, rows 58-xx immediately disappear. Continued scrolling brings in rows 0-57. 

Not all sure what might be causing this, but thought I would report.

My grid contains 500k rows btw.

### PR DESCRIPTION
**Pull request by soyuka**

### CODE REVIEW

**Comment by soyuka** [comment]
@tbranyen I had to bump stringdom, I think the guy patched the issue you had couple years back \o/. Lmk if I need to revert the last commit :).

https://github.com/jugglinmike/stringdom/pull/5

**Comment by tbranyen** [comment]
Nah that's fine, stringdom is just a lightweight jsdom replacement for us in this case, we could switch to jsdom even.

**Comment by soyuka** [comment]
I mean I have to bump because the commit you hard coded in the `package.json` can't be fetched anymore :|.

**Comment by tbranyen** [comment]
Hahaha, well that's no good. Lets merge what you have and see if jsdom is drop in later.

**Pull request merged**
